version: '3.8'

services:
  battletech-editor-app:
    build:
      context: ./battletech-editor-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # This SQLITE_DB_PATH must match the one defined in the Dockerfile and used by lib/db.js
      - SQLITE_DB_PATH=/usr/src/app/battletech_editor.sqlite
      # NODE_ENV can be set to 'production' for optimized builds if desired
      - NODE_ENV=development
    # Optional: If you want the database to persist across container restarts (for development)
    # you could mount a volume. For a "self-contained, works out of the box" setup where
    # the DB is initialized on each start, this is not strictly necessary.
    # volumes:
    #   - ./battletech_editor_data:/usr/src/app/data
    #   (If using this, SQLITE_DB_PATH would be /usr/src/app/data/battletech_editor.sqlite)
    # For now, we'll stick to the DB being inside the container and re-initialized on build.
