version: '3.8'

services:
  app:
    build:
      context: ./battletech-editor-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: battletech_user
      DB_PASSWORD: battletech_pass
      DB_NAME: battletech_editor
      DATABASE_URL: postgresql://battletech_user:battletech_pass@db:5432/battletech_editor
      NODE_ENV: production # Can be overridden for development
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3000/api # Assuming API routes are part of the Next.js app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: battletech_user
      POSTGRES_PASSWORD: battletech_pass
      POSTGRES_DB: battletech_editor
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql # Mount schema for auto-initialization
    ports:
      - "5433:5432" # Expose PostgreSQL on host port 5433 for external access if needed

volumes:
  pgdata: # Defines the named volume for persistent PostgreSQL data
