name: MegaMekLab CI with Code Coverage

on:
  push:
    branches: [master]

env:
  GRADLE_OPTS: "-Dscan.link.VCS=https://github.com/MegaMek/megameklab/commit/${{ github.sha }}"

jobs:
  code_coverage:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java-distribution: [temurin]
        java-version: [17]

    steps:
      - uses: actions/checkout@v4
        with:
          path: megameklab

      - name: Checkout MegaMek
        uses: actions/checkout@v4
        with:
          repository: MegaMek/megamek
          path: megamek

      - name: Set up ${{ matrix.java-distribution }} JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        working-directory: megameklab
        run: ./gradlew test

      - name: Upload Test Logs on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cd-failure-logs
          path: ./megameklab/megameklab/build/reports/

      - name: CodeCov.io Coverage Report
        uses: codecov/codecov-action@v5
        with:
          directory: ./megameklab/megameklab/build/reports/jacoco/test
          fail_ci_if_error: false
          verbose: true
